//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class periodos
    {
        public periodos()
        {
            this.periodos_feriados = new HashSet<periodos_feriados>();
            this.periodos_objetivos = new HashSet<periodos_objetivos>();
            this.periodos_semanas = new HashSet<periodos_semanas>();
            this.lancamentos = new HashSet<lancamentos>();
            this.metas_entradas = new HashSet<metas_entradas>();
            this.metas_faturamento = new HashSet<metas_faturamento>();
            this.metas_fluxo = new HashSet<metas_fluxo>();
            this.metas_fotografados = new HashSet<metas_fotografados>();
            this.metas_recebimento = new HashSet<metas_recebimento>();
        }
    
        public int id_periodo { get; set; }
        public Nullable<int> id_filial { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<int> mes { get; set; }
        public Nullable<System.DateTime> data_inicio { get; set; }
        public Nullable<System.DateTime> data_fim { get; set; }
        public Nullable<int> dias { get; set; }
    
        public virtual filiais filiais { get; set; }
        public virtual ICollection<periodos_feriados> periodos_feriados { get; set; }
        public virtual ICollection<periodos_objetivos> periodos_objetivos { get; set; }
        public virtual ICollection<periodos_semanas> periodos_semanas { get; set; }
        public virtual ICollection<lancamentos> lancamentos { get; set; }
        public virtual ICollection<metas_entradas> metas_entradas { get; set; }
        public virtual ICollection<metas_faturamento> metas_faturamento { get; set; }
        public virtual ICollection<metas_fluxo> metas_fluxo { get; set; }
        public virtual ICollection<metas_fotografados> metas_fotografados { get; set; }
        public virtual ICollection<metas_recebimento> metas_recebimento { get; set; }
    }
}
