//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPanel.Dados
{
    using System;
    
    public enum SpcTipoConsulta : int
    {
        Padrao = 1,
        UsaProgramada = 2,
        Tranferido = 3
    }
}
