//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACORDOREL
    {
        public int IDACORDO { get; set; }
        public short CODCOLIGADA { get; set; }
        public int IDLAN { get; set; }
        public int CLASSIFICACAO { get; set; }
        public string RECCREATEDBY { get; set; }
        public Nullable<System.DateTime> RECCREATEDON { get; set; }
        public string RECMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> RECMODIFIEDON { get; set; }
        public Nullable<int> IDBAIXA { get; set; }
        public decimal DESCONTOACORDO { get; set; }
        public decimal ACRESCIMOACORDO { get; set; }
        public decimal JUROSACORDO { get; set; }
    
        public virtual FACORDO FACORDO { get; set; }
        public virtual FLAN FLAN { get; set; }
    }
}
