//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACORDO
    {
        public FACORDO()
        {
            this.FACORDOREL = new HashSet<FACORDOREL>();
            this.FLANACORDO = new HashSet<FLANACORDO>();
        }
    
        public int IDACORDO { get; set; }
        public short CODCOLIGADA { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string OBSERVACAO { get; set; }
        public string USUARIO { get; set; }
        public string RECCREATEDBY { get; set; }
        public Nullable<System.DateTime> RECCREATEDON { get; set; }
        public string RECMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> RECMODIFIEDON { get; set; }
        public Nullable<short> CODCOLCFO { get; set; }
        public string CODCFO { get; set; }
        public Nullable<decimal> VALORDESCONTO { get; set; }
        public Nullable<decimal> VALORACRESCIMO { get; set; }
        public Nullable<decimal> TAXAJUROS { get; set; }
        public Nullable<short> JUROSFUTUROS { get; set; }
        public Nullable<short> QTDEPARCELAS { get; set; }
        public Nullable<System.DateTime> PRIMEIROVENCIMENTO { get; set; }
        public Nullable<System.DateTime> DATACANCELAMENTO { get; set; }
        public Nullable<short> INTERVALO { get; set; }
        public Nullable<short> MANTERDIAVENC { get; set; }
        public short STATUS { get; set; }
    
        public virtual FCFO FCFO { get; set; }
        public virtual GCOLIGADA GCOLIGADA { get; set; }
        public virtual ICollection<FACORDOREL> FACORDOREL { get; set; }
        public virtual ICollection<FLANACORDO> FLANACORDO { get; set; }
    }
}
