//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class GFILIAL
    {
        public GFILIAL()
        {
            this.FTB1 = new HashSet<FTB1>();
            this.TMOV = new HashSet<TMOV>();
            this.TMOV1 = new HashSet<TMOV>();
            this.TVEN = new HashSet<TVEN>();
            this.FLAN = new HashSet<FLAN>();
            this.FXCX = new HashSet<FXCX>();
            this.FXCX1 = new HashSet<FXCX>();
            this.FCXA = new HashSet<FCXA>();
            this.TITMMOV = new HashSet<TITMMOV>();
            this.PFUNC = new HashSet<PFUNC>();
        }
    
        public short CODCOLIGADA { get; set; }
        public short CODFILIAL { get; set; }
        public string NOMEFANTASIA { get; set; }
        public string CGC { get; set; }
        public string NOME { get; set; }
        public string INSCRICAOESTADUAL { get; set; }
        public string TELEFONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string RUA { get; set; }
        public string NUMERO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
        public string PAIS { get; set; }
        public string CEP { get; set; }
        public string CONTATO { get; set; }
        public string PRODUTORRURAL { get; set; }
        public Nullable<short> TIPORUA { get; set; }
        public Nullable<short> TIPOBAIRRO { get; set; }
        public string CODCALENDARIO { get; set; }
        public Nullable<int> IDIMAGEM { get; set; }
        public string CODMUNICIPIO { get; set; }
        public string LOCALIDADE { get; set; }
        public Nullable<short> RAMOATIVIDADE { get; set; }
        public string INSCMUN { get; set; }
        public string CODATIVFED { get; set; }
        public string CODATIVIDPRINC { get; set; }
        public string DESCATIVIDPRINC { get; set; }
        public string NUMREGJUNTA { get; set; }
        public string CAIXAPOSTAL { get; set; }
        public string CEPCAIXAPOSTAL { get; set; }
        public Nullable<System.DateTime> DATAREGJUNTA { get; set; }
        public Nullable<short> IDPAIS { get; set; }
        public string SUFRAMA { get; set; }
        public int ID { get; set; }
        public string IDINTEGRACAO { get; set; }
        public string RECCREATEDBY { get; set; }
        public Nullable<System.DateTime> RECCREATEDON { get; set; }
        public string RECMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> RECMODIFIEDON { get; set; }
        public string DDD { get; set; }
        public string DDDFAX { get; set; }
    
        public virtual ICollection<FTB1> FTB1 { get; set; }
        public virtual GCOLIGADA GCOLIGADA { get; set; }
        public virtual ICollection<TMOV> TMOV { get; set; }
        public virtual ICollection<TMOV> TMOV1 { get; set; }
        public virtual ICollection<TVEN> TVEN { get; set; }
        public virtual GETD GETD { get; set; }
        public virtual GMUNICIPIO GMUNICIPIO { get; set; }
        public virtual GPAIS GPAIS { get; set; }
        public virtual DTIPOBAIRRO DTIPOBAIRRO { get; set; }
        public virtual DTIPORUA DTIPORUA { get; set; }
        public virtual ICollection<FLAN> FLAN { get; set; }
        public virtual ICollection<FXCX> FXCX { get; set; }
        public virtual ICollection<FXCX> FXCX1 { get; set; }
        public virtual ICollection<FCXA> FCXA { get; set; }
        public virtual ICollection<TITMMOV> TITMMOV { get; set; }
        public virtual ICollection<PFUNC> PFUNC { get; set; }
    }
}
