//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCPG
    {
        public TCPG()
        {
            this.TMOV = new HashSet<TMOV>();
            this.TITMMOV = new HashSet<TITMMOV>();
            this.TPRODUTODEF = new HashSet<TPRODUTODEF>();
        }
    
        public short CODCOLIGADA { get; set; }
        public string CODCPG { get; set; }
        public string NOME { get; set; }
        public string ARREDPRIMOUULT { get; set; }
        public string ARREDDEZOUCENT { get; set; }
        public Nullable<short> NUMVETCONDICOES { get; set; }
        public Nullable<decimal> VALORPAGAMENTO1 { get; set; }
        public Nullable<short> QUANTASVEZES1 { get; set; }
        public Nullable<short> PERIODOEMDIAS1 { get; set; }
        public Nullable<short> PRAZO1 { get; set; }
        public string CONTAGEMDIAS1 { get; set; }
        public string TIPO1 { get; set; }
        public Nullable<decimal> VALORPAGAMENTO2 { get; set; }
        public Nullable<short> QUANTASVEZES2 { get; set; }
        public Nullable<short> PERIODOEMDIAS2 { get; set; }
        public Nullable<short> PRAZO2 { get; set; }
        public string CONTAGEMDIAS2 { get; set; }
        public string TIPO2 { get; set; }
        public Nullable<decimal> VALORPAGAMENTO3 { get; set; }
        public Nullable<short> QUANTASVEZES3 { get; set; }
        public Nullable<short> PERIODOEMDIAS3 { get; set; }
        public Nullable<short> PRAZO3 { get; set; }
        public string CONTAGEMDIAS3 { get; set; }
        public string TIPO3 { get; set; }
        public Nullable<decimal> VALORPAGAMENTO4 { get; set; }
        public Nullable<short> QUANTASVEZES4 { get; set; }
        public Nullable<short> PERIODOEMDIAS4 { get; set; }
        public Nullable<short> PRAZO4 { get; set; }
        public string CONTAGEMDIAS4 { get; set; }
        public string TIPO4 { get; set; }
        public Nullable<decimal> VALORPAGAMENTO5 { get; set; }
        public Nullable<short> QUANTASVEZES5 { get; set; }
        public Nullable<short> PERIODOEMDIAS5 { get; set; }
        public Nullable<short> PRAZO5 { get; set; }
        public string CONTAGEMDIAS5 { get; set; }
        public string TIPO5 { get; set; }
        public Nullable<decimal> DEFLATOR { get; set; }
        public string APLICACAOFRM { get; set; }
        public string CODFRMPRECO1 { get; set; }
        public string CODFRMPRECO2 { get; set; }
        public Nullable<short> DIACARENCIA { get; set; }
        public Nullable<decimal> TAXAJUROS { get; set; }
        public Nullable<short> JUROSCOMPOSTO { get; set; }
        public Nullable<short> PLANOPAGTO { get; set; }
        public Nullable<decimal> CAPITALIZMENSAL { get; set; }
        public Nullable<short> PLANOCOMPRA { get; set; }
        public Nullable<short> PLANOVENDA { get; set; }
        public Nullable<int> DIASVENCSEMANA { get; set; }
        public string CODFRMPRIMPARCELA { get; set; }
        public Nullable<short> INATIVO { get; set; }
        public string RECCREATEDBY { get; set; }
        public Nullable<System.DateTime> RECCREATEDON { get; set; }
        public string RECMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> RECMODIFIEDON { get; set; }
    
        public virtual GCOLIGADA GCOLIGADA { get; set; }
        public virtual ICollection<TMOV> TMOV { get; set; }
        public virtual ICollection<TITMMOV> TITMMOV { get; set; }
        public virtual ICollection<TPRODUTODEF> TPRODUTODEF { get; set; }
    }
}
