//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.CService.Dados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CServicosEntities : DbContext
    {
        public CServicosEntities()
            : base("name=CServicosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<env_envelopes> env_envelopes { get; set; }
        public virtual DbSet<env_status> env_status { get; set; }
        public virtual DbSet<env_envelopes_fotos> env_envelopes_fotos { get; set; }
        public virtual DbSet<env_envelopes_mov> env_envelopes_mov { get; set; }
        public virtual DbSet<env_studios> env_studios { get; set; }
        public virtual DbSet<env_laboratoristas> env_laboratoristas { get; set; }
        public virtual DbSet<env_laboratoristas_envelopes> env_laboratoristas_envelopes { get; set; }
        public virtual DbSet<env_tamanhos> env_tamanhos { get; set; }
        public virtual DbSet<env_albuns> env_albuns { get; set; }
        public virtual DbSet<env_molduras> env_molduras { get; set; }
        public virtual DbSet<env_usuarios> env_usuarios { get; set; }
        public virtual DbSet<env_usuarios_grupos> env_usuarios_grupos { get; set; }
    }
}
