//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.CService.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class env_tamanhos
    {
        public env_tamanhos()
        {
            this.env_molduras = new HashSet<env_molduras>();
        }
    
        public int id_tamanho { get; set; }
        public string nome { get; set; }
        public Nullable<int> prazo { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<bool> perm_quant_fotos { get; set; }
        public Nullable<bool> perm_album { get; set; }
        public Nullable<bool> perm_moldura { get; set; }
        public Nullable<bool> perm_paspatur { get; set; }
        public Nullable<decimal> valor_paspatur { get; set; }
        public Nullable<bool> perm_sacola_branca { get; set; }
        public Nullable<decimal> valor_sacola_branca { get; set; }
        public Nullable<bool> perm_sacola_verde { get; set; }
        public Nullable<decimal> valor_sacola_verde { get; set; }
        public Nullable<bool> exibir_studio { get; set; }
        public string comissaoTipo { get; set; }
        public Nullable<decimal> comissaoPeso { get; set; }
        public string descontoTipo { get; set; }
        public Nullable<decimal> descontoPeso { get; set; }
    
        public virtual ICollection<env_molduras> env_molduras { get; set; }
    }
}
