//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agencia
    {
        public Agencia()
        {
            this.Conta = new HashSet<Conta>();
        }
    
        public int IdAgencia { get; set; }
        public int IdBanco { get; set; }
        public int IdCidade { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string Gerente { get; set; }
        public string Email { get; set; }
        public bool IsAtivo { get; set; }
    
        public virtual ICollection<Conta> Conta { get; set; }
        public virtual Banco Banco { get; set; }
        public virtual Cidade Cidade { get; set; }
    }
}
