//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendamentoMov
    {
        public int IdAgendamentoMov { get; set; }
        public int IdAgendamento { get; set; }
        public int IdUsuario { get; set; }
        public EnumAgendamentoStatus Status { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan Hora { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Agendamento Agendamento { get; set; }
        public virtual AgendamentoStatus AgendamentoStatus { get; set; }
    }
}
