//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conta
    {
        public Conta()
        {
            this.ContaCaixa = new HashSet<ContaCaixa>();
        }
    
        public int IdConta { get; set; }
        public int IdAgencia { get; set; }
        public string Nome { get; set; }
        public string ContaNumero { get; set; }
        public string ContaDigito { get; set; }
        public string CarteiraNumero { get; set; }
        public string CarteiraDigito { get; set; }
        public string CedenteNome { get; set; }
        public string CedenteCnjp { get; set; }
        public string CedenteNumero { get; set; }
        public string CedenteDigito { get; set; }
        public string ConvenioNumero { get; set; }
        public string ConvenioDigito { get; set; }
        public EnumContaTipo TipoConta { get; set; }
        public EnumCobrancaTipo TipoCobranca { get; set; }
        public bool IsAtivo { get; set; }
    
        public virtual ICollection<ContaCaixa> ContaCaixa { get; set; }
        public virtual Agencia Agencia { get; set; }
    }
}
