//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContaCaixa
    {
        public ContaCaixa()
        {
            this.Lancamento = new HashSet<Lancamento>();
            this.Extrato = new HashSet<Extrato>();
            this.Renegociacao = new HashSet<Renegociacao>();
            this.Retorno = new HashSet<Retorno>();
        }
    
        public int IdContaCaixa { get; set; }
        public int IdFilial { get; set; }
        public int IdConta { get; set; }
        public string Nome { get; set; }
        public bool IsCaixa { get; set; }
        public bool IsPadrao { get; set; }
        public bool IsAtivo { get; set; }
    
        public virtual Filial Filial { get; set; }
        public virtual Conta Conta { get; set; }
        public virtual ICollection<Lancamento> Lancamento { get; set; }
        public virtual ICollection<Extrato> Extrato { get; set; }
        public virtual ICollection<Renegociacao> Renegociacao { get; set; }
        public virtual ICollection<Retorno> Retorno { get; set; }
    }
}
