//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cupom
    {
        public Cupom()
        {
            this.TelemarketingAgenda = new HashSet<TelemarketingAgenda>();
            this.TelemarketingMov = new HashSet<TelemarketingMov>();
            this.Indicacao = new HashSet<Indicacao>();
            this.Agendamento = new HashSet<Agendamento>();
        }
    
        public int IdCupom { get; set; }
        public int IdParceria { get; set; }
        public Nullable<EnumTelemarketingStatus> IdStatusTele { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> IdUsuarioTele { get; set; }
        public Nullable<System.DateTime> DataTele { get; set; }
        public System.DateTime Data { get; set; }
        public System.DateTime DataPreenchimento { get; set; }
        public EnumCupomStatus Status { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Endereco { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string Obs { get; set; }
        public bool IsAtivo { get; set; }
        public Nullable<System.DateTime> UltimaUtilizacao { get; set; }
        public Nullable<int> IdCupomWeb { get; set; }
        public Nullable<bool> IsDescartado { get; set; }
        public Nullable<System.DateTime> DataDescartado { get; set; }
        public Nullable<bool> IsAgendado { get; set; }
        public Nullable<System.DateTime> DataAgendado { get; set; }
        public Nullable<bool> IsLembrete { get; set; }
        public Nullable<System.DateTime> DataLembrete { get; set; }
        public string OperadoraTelefone { get; set; }
        public string OperadoraCelular { get; set; }
    
        public virtual TelemarketingStatus TelemarketingStatus { get; set; }
        public virtual Usuario UsuarioTele { get; set; }
        public virtual Parceria Parceria { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<TelemarketingAgenda> TelemarketingAgenda { get; set; }
        public virtual ICollection<TelemarketingMov> TelemarketingMov { get; set; }
        public virtual ICollection<Indicacao> Indicacao { get; set; }
        public virtual ICollection<Agendamento> Agendamento { get; set; }
        public virtual CupomStatus CupomStatus { get; set; }
    }
}
