//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    
    public enum EnumCupomStatus : int
    {
        EmAberto = 1,
        Agendado = 2,
        Faltante = 3,
        Cancelado = 4,
        Descartado = 5,
        Confirmado = 6,
        Atendido = 7,
        Desligado = 8,
        JaFotografou = 9,
        NaoQuer = 10,
        NumeroErrado = 11,
        NaoAtende = 12
    }
}
