//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    
    public enum EnumStatusServico : int
    {
        AguardandoLiberacao = 1,
        EnviadoLaboratorio = 2,
        Impresso = 3,
        Laboratorio = 4,
        Envio = 5,
        ControleQualidade = 6,
        FotoAcabamento = 7,
        Faturamento = 8,
        Embalagem = 9,
        EnviadoEstudio = 10,
        RecebidoLaboratorio = 11,
        EntregueCliente = 12,
        Cancelado = 0
    }
}
