//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    
    public enum EnumTelemarketingStatus : int
    {
        Distribuido = 2,
        Expirado = 3,
        Agendado = 4,
        Descartado = 5,
        Finalizado = 6,
        Faltante = 7
    }
}
