//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    
    public enum EnumStatusLanc : int
    {
        EmAberto = 1,
        Baixado = 2,
        BaixadoAcordo = 3,
        Cancelado = 4,
        AguardandoLiberacao = 5
    }
}
