//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    
    public enum EnumRelatorioTipo : int
    {
        Venda_Envelope = 0,
        Venda_ServicosContratados = 1,
        Venda_Contrato = 2,
        Venda_Boleto = 3,
        Venda_Troca = 4,
        Venda_Aditamento = 5,
        Atendimento_Ficha = 6,
        Atendimento_UsoImagem = 7,
        Atendimento_Autorizacao = 8,
        Concurso_TopMirim = 9,
        Marketing_CuponsXUsuario = 10,
        Fotog_Periodo = 11,
        Atendimento_AtendidoXPeriodo = 12,
        Concurso_Garota = 13,
        Venda_ControlePagamento = 14,
        Venda_ComprovanteEntrada = 15,
        Concurso_BabyShow = 16,
        Concurso_Newborn = 17,
        Venda_Cancelamento = 18,
        Venda_Recibo = 19
    }
}
