//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    
    public enum EnumPgtoTipo : int
    {
        Dinheiro = 1,
        Debito = 2,
        Credito = 3,
        Deposito = 4,
        Cheque = 5,
        Boleto = 6
    }
}
