//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    
    public enum EnumConvenioTipo : int
    {
        Parceria = 1,
        Concurso = 2,
        EMarketing = 3,
        EndoMarketing = 4,
        Midia = 5,
        Carta = 6,
        ClubePremios = 7,
        Direto = 8,
        Indicacao = 9,
        PosVenda = 10,
        IndicacaoEscritorio = 11
    }
}
