//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public Evento()
        {
            this.VendaEvento = new HashSet<VendaEvento>();
        }
    
        public int IdEvento { get; set; }
        public int IdParceria { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
    
        public virtual Parceria Parceria { get; set; }
        public virtual ICollection<VendaEvento> VendaEvento { get; set; }
    }
}
