//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filial
    {
        public Filial()
        {
            this.Pedido = new HashSet<Pedido>();
            this.UsuarioFilial = new HashSet<UsuarioFilial>();
            this.Parceria = new HashSet<Parceria>();
            this.Atendimento = new HashSet<Atendimento>();
            this.ContaCaixa = new HashSet<ContaCaixa>();
            this.Lancamento = new HashSet<Lancamento>();
            this.Agenda = new HashSet<Agenda>();
            this.Config = new HashSet<Config>();
            this.Renegociacao = new HashSet<Renegociacao>();
            this.Retorno = new HashSet<Retorno>();
            this.TabelaFilial = new HashSet<TabelaFilial>();
            this.Backup = new HashSet<Backup>();
        }
    
        public int IdFilial { get; set; }
        public int IdGrupoEmpresa { get; set; }
        public int IdCidade { get; set; }
        public string RazaoSocial { get; set; }
        public string NomeFantasia { get; set; }
        public string Cnpj { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cep { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string Fax { get; set; }
        public bool IsAtivo { get; set; }
    
        public virtual GrupoEmpresa GrupoEmpresa { get; set; }
        public virtual Cidade Cidade { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
        public virtual ICollection<UsuarioFilial> UsuarioFilial { get; set; }
        public virtual ICollection<Parceria> Parceria { get; set; }
        public virtual ICollection<Atendimento> Atendimento { get; set; }
        public virtual ICollection<ContaCaixa> ContaCaixa { get; set; }
        public virtual ICollection<Lancamento> Lancamento { get; set; }
        public virtual ICollection<Agenda> Agenda { get; set; }
        public virtual ICollection<Config> Config { get; set; }
        public virtual ICollection<Renegociacao> Renegociacao { get; set; }
        public virtual ICollection<Retorno> Retorno { get; set; }
        public virtual ICollection<TabelaFilial> TabelaFilial { get; set; }
        public virtual ICollection<Backup> Backup { get; set; }
    }
}
