//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoEmpresa
    {
        public GrupoEmpresa()
        {
            this.Filial = new HashSet<Filial>();
        }
    
        public int IdGrupoEmpresa { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public bool IsFranquia { get; set; }
        public bool IsAtivo { get; set; }
    
        public virtual ICollection<Filial> Filial { get; set; }
    }
}
