//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServicoMov
    {
        public int IdMov { get; set; }
        public int IdOrdemServico { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime Data { get; set; }
        public EnumStatusServico Status { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual OrdemServico OrdemServico { get; set; }
        public virtual OrdemStatus OrdemStatus { get; set; }
    }
}
