//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.ProdutoServico = new HashSet<ProdutoServico>();
            this.VendaItem = new HashSet<VendaItem>();
        }
    
        public int IdProduto { get; set; }
        public int IdTabela { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> Custo { get; set; }
        public bool IsAtivo { get; set; }
    
        public virtual Tabela Tabela { get; set; }
        public virtual ICollection<ProdutoServico> ProdutoServico { get; set; }
        public virtual ICollection<VendaItem> VendaItem { get; set; }
    }
}
