//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessaoPasta
    {
        public SessaoPasta()
        {
            this.Foto = new HashSet<Foto>();
            this.SessaoPasta1 = new HashSet<SessaoPasta>();
        }
    
        public int IdSessaoPasta { get; set; }
        public Nullable<int> IdPastaPai { get; set; }
        public string Nome { get; set; }
        public bool IsDefault { get; set; }
        public int IdSessao { get; set; }
        public string Caminho { get; set; }
    
        public virtual ICollection<Foto> Foto { get; set; }
        public virtual ICollection<SessaoPasta> SessaoPasta1 { get; set; }
        public virtual SessaoPasta SessaoPasta2 { get; set; }
        public virtual Sessao Sessao { get; set; }
    }
}
