//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelaFilial
    {
        public int IdTabelaFilial { get; set; }
        public int IdFilial { get; set; }
        public int IdTabela { get; set; }
    
        public virtual Filial Filial { get; set; }
        public virtual Tabela Tabela { get; set; }
    }
}
