//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelemarketingMov
    {
        public int IdTelemarketingMov { get; set; }
        public int IdCupom { get; set; }
        public Nullable<EnumTelemarketingStatus> IdStatus { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Cupom Cupom { get; set; }
        public virtual TelemarketingStatus TelemarketingStatus { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
