//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioGrupo
    {
        public UsuarioGrupo()
        {
            this.UsuarioFilial = new HashSet<UsuarioFilial>();
        }
    
        public int IdUsuarioGrupo { get; set; }
        public string Nome { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsGerente { get; set; }
        public bool IsSupervisor { get; set; }
        public bool IsFinanceiro { get; set; }
        public bool IsComercial { get; set; }
        public bool IsProducao { get; set; }
        public bool IsMarketing { get; set; }
        public bool IsAtivo { get; set; }
    
        public virtual ICollection<UsuarioFilial> UsuarioFilial { get; set; }
    }
}
