//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canaan.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendaFoto
    {
        public int IdVendaFoto { get; set; }
        public int IdPedido { get; set; }
        public int IdFoto { get; set; }
    
        public virtual Venda Venda { get; set; }
        public virtual Foto Foto { get; set; }
    }
}
